# Generated by Django 4.2.20 on 2025-10-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Remove extra columns that don't exist in the QuoteItem model
            sql="""
                ALTER TABLE gestion_api_quoteitem 
                DROP COLUMN IF EXISTS amount,
                DROP COLUMN IF EXISTS date,
                DROP COLUMN IF EXISTS reference,
                DROP COLUMN IF EXISTS description,
                DROP COLUMN IF EXISTS client_id,
                DROP COLUMN IF EXISTS created_by_id,
                DROP COLUMN IF EXISTS sale_id;
            """,
            reverse_sql="""
                -- This migration is not reversible as we're removing data
                -- If you need to reverse, restore from backup
            """
        ),
    ]
