# Generated by Django 4.2.20 on 2025-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0002_stocksupply_paid_amount_stocksupply_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercashpayment',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
