# Generated by Django 4.2.20 on 2025-05-03 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_api', '0005_alter_stock_updated_at'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='stock',
    #         name='created_by',
    #         field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
    #     ),
    # ]
