# Generated by Django 4.2.20 on 2025-05-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0006_add_created_by_field_to_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_api.client'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='gestion_api.sale'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stocksupply',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
