# Generated by Django 4.2.20 on 2025-05-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0007_cashreceipt_client_cashreceipt_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('overpaid', 'Surpayé')], default='unpaid', max_length=20),
        ),
    ]
