# Generated by Django 4.2.20 on 2025-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0010_update_sale_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpayment',
            options={'verbose_name': 'Account Payment', 'verbose_name_plural': 'Account Payments'},
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='transaction_type',
            field=models.CharField(choices=[('client_payment', 'Règlement client'), ('supplier_payment', 'Règlement fournisseur'), ('transfer_in', 'Virement entrant'), ('transfer_out', 'Virement sortant'), ('cash_receipt', 'Encaissement'), ('cash_payment', 'Décaissement'), ('expense', 'Dépense'), ('sale', 'Vente'), ('purchase', 'Achat'), ('deposit', 'Dépôt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('payment_pending', 'Paiement en attente'), ('paid', 'Payé'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='workflow_state',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('payment_pending', 'Paiement en attente'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=50),
        ),
    ]
