# Generated by Django 4.2.20 on 2025-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0012_update_draft_workflow_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='workflow_state',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('payment_pending', 'Paiement en attente'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=50),
        ),
    ]
