# Generated by Django 4.2.20 on 2025-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0013_alter_sale_workflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('confirmed', 'Confirmé'), ('payment_pending', 'Paiement en attente'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='workflow_state',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('confirmed', 'Confirmé'), ('payment_pending', 'Paiement en attente'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=50),
        ),
    ]
