# Generated by Django 4.2.20 on 2025-06-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0014_alter_sale_status_alter_sale_workflow_state'),
        ('gestion_api', '0014_update_sale_default_status'),
    ]

    operations = [
    ]
