# Generated by Django 4.2.20 on 2025-07-08 23:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_api', '0016_sale_paid_amount_sale_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayment',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overpaid', 'Overpaid')], default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoicePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='gestion_api.accountpayment')),
                ('cash_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='gestion_api.cashreceipt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='gestion_api.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment Allocation',
                'verbose_name_plural': 'Invoice Payment Allocations',
            },
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('account_payment__isnull', False), ('cash_receipt__isnull', False), _connector='OR'), name='allocation_has_payment_source'),
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('account_payment__isnull', False), ('cash_receipt__isnull', False), _negated=True), name='allocation_single_payment_source'),
        ),
    ]
