# Generated by Django 4.2.20 on 2025-07-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0017_accountpayment_allocated_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpayment',
            name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='cashreceipt',
            name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_api.unitofmeasure'),
        ),
        migrations.DeleteModel(
            name='InvoicePaymentAllocation',
        ),
    ]
