# Generated by Django 4.2.20 on 2025-07-26 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0018_remove_accountpayment_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(db_column='unit', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_api.unitofmeasure'),
        ),
    ]
