# Generated by Django 4.2.20 on 2025-07-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0019_add_allocated_amount_to_cashreceipt'),
    ]

    operations = [
        # This migration ensures the payment_status column is properly removed
        # from the invoice table if it still exists
        migrations.RunSQL(
            "ALTER TABLE gestion_api_invoice DROP COLUMN IF EXISTS payment_status;",
            reverse_sql="ALTER TABLE gestion_api_invoice ADD COLUMN payment_status VARCHAR(20) DEFAULT 'unpaid';"
        ),
    ]
