# Generated by Django 4.2.20 on 2025-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0021_add_is_converted_to_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('paid', 'Payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='is_converted',
            field=models.BooleanField(default=False, help_text='Si ce devis a été converti en vente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], default='draft', max_length=20),
        ),
    ]
