# Generated by Django 4.2.20 on 2025-08-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0022_update_quote_invoice_choices_to_french'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='gestion_api.sale'),
        ),
    ]
