# Generated by Django 4.2.20 on 2025-08-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0023_alter_cashreceipt_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayment',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_api.sale'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='gestion_api.sale'),
        ),
    ]
