# Generated by Django 4.2.20 on 2025-09-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0024_alter_accountpayment_sale_alter_invoice_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcard',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='stockcard',
            name='unit_price',
        ),
    ]
