# Generated by Django 4.2.20 on 2025-10-11 13:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_raw_material', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_products', to='app_settings.productcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_products_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(db_column='unit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_products', to='app_settings.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'gestion_api_product',
            },
        ),
        migrations.CreateModel(
            name='StockSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiellement reçu'), ('received', 'Reçu'), ('cancelled', 'Annulé')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Non payé'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('overpaid', 'Surpayé')], default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stock_supplies_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_supplies', to='partners.supplier')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_supplies', to='core.zone')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'db_table': 'gestion_api_stocksupply',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='partners.supplier')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_supplies', to='core.zone')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'db_table': 'gestion_api_supply',
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='inventory.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supply')),
            ],
            options={
                'verbose_name': "Élément d'approvisionnement",
                'verbose_name_plural': "Éléments d'approvisionnement",
                'db_table': 'gestion_api_supplyitem',
            },
        ),
        migrations.CreateModel(
            name='StockSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_supply_items', to='inventory.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocksupply')),
            ],
            options={
                'verbose_name': "Élément d'approvisionnement",
                'verbose_name_plural': "Éléments d'approvisionnement",
                'db_table': 'gestion_api_stocksupplyitem',
            },
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('supply', 'Approvisionnement'), ('sale', 'Vente'), ('transfer_in', 'Transfert entrant'), ('transfer_out', 'Transfert sortant'), ('inventory', "Ajustement d'inventaire"), ('production', 'Production'), ('return', 'Retour')], max_length=20)),
                ('reference', models.CharField(max_length=50)),
                ('quantity_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_cards', to='inventory.product')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_cards', to='core.zone')),
            ],
            options={
                'verbose_name': 'Fiche de stock',
                'verbose_name_plural': 'Fiches de stock',
                'db_table': 'gestion_api_stockcard',
                'ordering': ['product', 'zone', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stocks_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='core.zone')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'gestion_api_stock',
                'unique_together': {('product', 'zone')},
            },
        ),
    ]
