# Generated by Django 4.2.20 on 2025-10-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('treasury', '0002_supplierpayment_suppliercashpayment_clientpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercashpayment',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.stocksupply'),
        ),
    ]
